version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      strapi:
        patterns:
          - "@strapi/*"
      react:
        patterns:
          - "react-dom"
          - "react"
    # Too much noise with patch releases...
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
